version: "3"
services:

  mongo:
    image: mongo:3.4.4

  subscription-api:
    image: rezme/resume-subscription-api
    ports:
      - 8082:80
    environment:
      - APP_PORT=80
      - MONGO_URI=mongodb://mongo/subscrition
    volumes:
      - /var/lib/mongo/db/subscription
    depends_on:
      - mongo

  token-api:
    image: rezme/resume-token-api
    ports:
      - 8081:80
    environment:
      - APP_PORT=80
      - MONGO_URI=mongodb://mongo/tokens
      - JWT_SECRET=foo_bar
    volumes:
      - /var/lib/mongo/db/tokens
    depends_on:
      - mongo
      - subscription-api

  core-api:
    image: rezme/resume-core-api
    ports:
      - 8080:80
    environment:
      - APP_PORT=80
      - MONGO_URI=mongodb://mongo/resume
      - JWT_TOKEN_HEADER=x-jwt-token
      - JWT_SECRET=foo_bar
    volumes:
      - /var/lib/mongo/db/resume
    depends_on:
      - mongo
      - token-api
